In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

In [2]:
def data_frame(data, sep):
    df = pd.read_csv(data, sep=";")
    return df

In [3]:
# read CSV file onshore Wind
df_wind = data_frame("timeseriesdata/ts_HH_generationData_2030_onshoreWind.csv", sep=";")
print(df_wind.tail(20))

      onshoreWind  Handewitt  Schuby west  Uw Husum Nord  Suderdonn  \
8740         8741     40.486       16.943              0     14.544
8741         8742     40.597       17.125              0     14.664
8742         8743     42.704       18.699              0     15.826
8743         8744     45.588       19.385              0     16.526
8744         8745     44.368       19.784              0     17.577
8745         8746     46.698       20.495              0     17.928
8746         8747     47.807       20.889              0     18.398
8747         8748     48.805       21.631              0     19.338
8748         8749     47.141       20.899              0     18.748
8749         8750     48.140       21.575              0     19.218
8750         8751     48.140       21.227              0     18.748
8751         8752     48.583       21.883              0     19.449
8752         8753     44.479       19.779              0     17.347
8753         8754     47.363       21.913              0     19.688
8754         8755     46.143       20.410              0     17.928
8755         8756     47.141       20.748              0     18.398
8756         8757     47.141       20.662              0     18.158
8757         8758     47.696       21.207              0     18.748
8758         8759     48.361       20.889              0     18.398
8759         8760     46.476       21.434              0     19.099

      Heide west  Brunsbuttel  itzehoe West  Klixbull Sud  Nielbull  Lubeck  \
8740           0            0         1.278         8.430         0       0
8741           0            0         1.345         8.319         0       0
8742           0            0         1.446         8.652         0       0
8743           0            0         1.715         8.763         0       0
8744           0            0         2.084         9.206         0       0
8745           0            0         2.252         9.428         0       0
8746           0            0         2.353         9.428         0       0
8747           0            0         2.656         9.761         0       0
8748           0            0         2.555         9.761         0       0
8749           0            0         2.656         9.872         0       0
8750           0            0         2.387         9.539         0       0
8751           0            0         2.555         9.761         0       0
8752           0            0         2.017         9.317         0       0
8753           0            0         2.656         9.872         0       0
8754           0            0         2.185         9.428         0       0
8755           0            0         2.252         9.539         0       0
8756           0            0         2.219         9.428         0       0
8757           0            0         2.320         9.539         0       0
8758           0            0         2.252         9.539         0       0
8759           0            0         2.454         9.761         0       0

      Siems  Jardelund  Uw Weesby  Kiel West  Breklum  Horstedt  Oldersbek  \
8740      0      6.943          0          0        0         0     25.667
8741      0      6.943          0          0        0         0     24.591
8742      0      7.302          0          0        0         0     26.147
8743      0      7.781          0          0        0         0     27.099
8744      0      8.859          0          0        0         0     28.445
8745      0      9.697          0          0        0         0     31.138
8746      0      9.697          0          0        0         0     31.158
8747      0     10.295          0          0        0         0     32.297
8748      0     10.175          0          0        0         0     32.217
8749      0     10.295          0          0        0         0     31.428
8750      0      9.697          0          0        0         0     30.940
8751      0     10.056          0          0        0         0     31.781
8752      0      9.218          0          0        0         0     30.171
8753      0     10.295          0          0        0         0     32.245
8754      0      9.337          0          0        0         0     30.171
8755      0      9.577          0          0        0         0     30.980
8756      0      9.457          0          0        0         0     30.591
8757      0      9.457          0          0        0         0     30.162
8758      0      9.577          0          0        0         0     30.571
8759      0      9.816          0          0        0         0     31.360

      Rendsburg Nord
8740           6.584
8741           6.225
8742           6.824
8743           7.422
8744           8.021
8745           9.816
8746           9.816
8747          10.175
8748          10.175
8749           9.098
8750           9.218
8751           9.816
8752           8.859
8753          10.056
8754           8.978
8755           9.337
8756           9.337
8757           9.098
8758           9.337
8759           9.577

In [4]:
# read CSV file photovoltaics
df_photovoltaics = data_frame("timeseriesdata/ts_HH_generationData_2030_photovoltaics.csv", sep=";")
print(df_photovoltaics.tail(30))

      photovoltaics  Handewitt  Schuby west  Uw Husum Nord  Suderdonn  \
8730           8731      0.000        0.000          0.000      0.000
8731           8732      0.000        0.000          0.000      0.000
8732           8733      0.000        0.000          0.000      0.000
8733           8734      0.000        0.000          0.000      0.000
8734           8735      0.000        0.000          0.000      0.000
8735           8736      0.000        0.000          0.000      0.000
8736           8737      0.000        0.000          0.000      0.000
8737           8738      0.000        0.000          0.000      0.000
8738           8739      0.000        0.000          0.000      0.000
8739           8740      0.000        0.000          0.000      0.000
8740           8741      0.000        0.000          0.000      0.000
8741           8742      0.000        0.000          0.000      0.000
8742           8743      0.000        0.000          0.000      0.000
8743           8744      0.000        0.000          0.000      0.000
8744           8745      0.290        0.113          0.113      0.113
8745           8746      1.205        0.499          0.499      0.499
8746           8747      1.833        0.640          0.640      0.640
8747           8748      1.772        0.263          0.263      0.263
8748           8749      0.719        0.179          0.179      0.179
8749           8750      0.403        0.099          0.099      0.099
8750           8751      0.054        0.013          0.013      0.013
8751           8752      0.000        0.000          0.000      0.000
8752           8753      0.000        0.000          0.000      0.000
8753           8754      0.000        0.000          0.000      0.000
8754           8755      0.000        0.000          0.000      0.000
8755           8756      0.000        0.000          0.000      0.000
8756           8757      0.000        0.000          0.000      0.000
8757           8758      0.000        0.000          0.000      0.000
8758           8759      0.000        0.000          0.000      0.000
8759           8760      0.000        0.000          0.000      0.000

      Heide west  Brunsbuttel  itzehoe West  Klixbull Sud  Nielbull  ...  \
8730       0.000        0.000         0.000         0.000     0.000  ...
8731       0.000        0.000         0.000         0.000     0.000  ...
8732       0.000        0.000         0.000         0.000     0.000  ...
8733       0.000        0.000         0.000         0.000     0.000  ...
8734       0.000        0.000         0.000         0.000     0.000  ...
8735       0.000        0.000         0.000         0.000     0.000  ...
8736       0.000        0.000         0.000         0.000     0.000  ...
8737       0.000        0.000         0.000         0.000     0.000  ...
8738       0.000        0.000         0.000         0.000     0.000  ...
8739       0.000        0.000         0.000         0.000     0.000  ...
8740       0.000        0.000         0.000         0.000     0.000  ...
8741       0.000        0.000         0.000         0.000     0.000  ...
8742       0.000        0.000         0.000         0.000     0.000  ...
8743       0.000        0.000         0.000         0.000     0.000  ...
8744       0.117        0.117         0.117         0.170     0.170  ...
8745       0.499        0.499         0.499         0.728     0.728  ...
8746       0.602        0.602         0.602         0.910     0.910  ...
8747       0.235        0.235         0.235         0.349     0.349  ...
8748       0.154        0.154         0.154         0.252     0.252  ...
8749       0.080        0.080         0.080         0.124     0.124  ...
8750       0.010        0.010         0.010         0.016     0.016  ...
8751       0.000        0.000         0.000         0.000     0.000  ...
8752       0.000        0.000         0.000         0.000     0.000  ...
8753       0.000        0.000         0.000         0.000     0.000  ...
8754       0.000        0.000         0.000         0.000     0.000  ...
8755       0.000        0.000         0.000         0.000     0.000  ...
8756       0.000        0.000         0.000         0.000     0.000  ...
8757       0.000        0.000         0.000         0.000     0.000  ...
8758       0.000        0.000         0.000         0.000     0.000  ...
8759       0.000        0.000         0.000         0.000     0.000  ...

      St lorenz sud  Bad Schwartau west  St lorenz Nord  Strecknitz  \
8730          0.000               0.000           0.000       0.000
8731          0.000               0.000           0.000       0.000
8732          0.000               0.000           0.000       0.000
8733          0.000               0.000           0.000       0.000
8734          0.000               0.000           0.000       0.000
8735          0.000               0.000           0.000       0.000
8736          0.000               0.000           0.000       0.000
8737          0.000               0.000           0.000       0.000
8738          0.000               0.000           0.000       0.000
8739          0.000               0.000           0.000       0.000
8740          0.000               0.000           0.000       0.000
8741          0.000               0.000           0.000       0.000
8742          0.000               0.000           0.000       0.000
8743          0.000               0.000           0.000       0.000
8744          0.071               0.311           0.118       0.118
8745          0.300               1.284           0.501       0.501
8746          0.356               1.977           0.593       0.593
8747          0.140               0.835           0.234       0.234
8748          0.087               0.476           0.145       0.145
8749          0.046               0.261           0.077       0.077
8750          0.006               0.035           0.010       0.010
8751          0.000               0.000           0.000       0.000
8752          0.000               0.000           0.000       0.000
8753          0.000               0.000           0.000       0.000
8754          0.000               0.000           0.000       0.000
8755          0.000               0.000           0.000       0.000
8756          0.000               0.000           0.000       0.000
8757          0.000               0.000           0.000       0.000
8758          0.000               0.000           0.000       0.000
8759          0.000               0.000           0.000       0.000

      lubeck Genin  Bad Oldesloe  Genin sud  Marli  Einfeld  Neumunster nord
8730         0.000         0.000      0.000  0.000    0.000             0.000
8731         0.000         0.000      0.000  0.000    0.000             0.000
8732         0.000         0.000      0.000  0.000    0.000             0.000
8733         0.000         0.000      0.000  0.000    0.000             0.000
8734         0.000         0.000      0.000  0.000    0.000             0.000
8735         0.000         0.000      0.000  0.000    0.000             0.000
8736         0.000         0.000      0.000  0.000    0.000             0.000
8737         0.000         0.000      0.000  0.000    0.000             0.000
8738         0.000         0.000      0.000  0.000    0.000             0.000
8739         0.000         0.000      0.000  0.000    0.000             0.000
8740         0.000         0.000      0.000  0.000    0.000             0.000
8741         0.000         0.000      0.000  0.000    0.000             0.000
8742         0.000         0.000      0.000  0.000    0.000             0.000
8743         0.000         0.000      0.000  0.000    0.000             0.000
8744         0.118         0.130      0.130  0.032    0.032             0.032
8745         0.501         0.526      0.526  0.135    0.135             0.135
8746         0.593         1.036      1.036  0.160    0.160             0.160
8747         0.234         0.426      0.426  0.063    0.063             0.063
8748         0.145         0.244      0.244  0.039    0.039             0.039
8749         0.077         0.134      0.134  0.021    0.021             0.021
8750         0.010         0.018      0.018  0.003    0.003             0.003
8751         0.000         0.000      0.000  0.000    0.000             0.000
8752         0.000         0.000      0.000  0.000    0.000             0.000
8753         0.000         0.000      0.000  0.000    0.000             0.000
8754         0.000         0.000      0.000  0.000    0.000             0.000
8755         0.000         0.000      0.000  0.000    0.000             0.000
8756         0.000         0.000      0.000  0.000    0.000             0.000
8757         0.000         0.000      0.000  0.000    0.000             0.000
8758         0.000         0.000      0.000  0.000    0.000             0.000
8759         0.000         0.000      0.000  0.000    0.000             0.000

[30 rows x 38 columns]

In [5]:
# read CSV file conventionalLoads
df_conventionalLoads = data_frame("timeseriesdata/ts_HH_loadData_2030_conventionalLoad_households.csv", sep=";")
print(df_conventionalLoads.head(50))

    conventionalLoad_households  Handewitt  Schuby west  Uw Husum Nord  \
0                             1      9.646        9.646          5.942
1                             2      7.147        7.147          4.402
2                             3      6.342        6.342          3.905
3                             4      5.809        5.809          3.576
4                             5      5.488        5.488          3.378
5                             6      5.675        5.675          3.493
6                             7      6.396        6.396          3.937
7                             8      9.939        9.939          6.121
8                             9     17.396       17.396         10.717
9                            10     23.163       23.163         14.271
10                           11     27.726       27.726         17.084
11                           12     30.444       30.444         18.760
12                           13     27.202       27.202         16.762
13                           14     21.122       21.122         13.016
14                           15     17.547       17.547         10.812
15                           16     15.452       15.452          9.521
16                           17     16.267       16.267         10.023
17                           18     21.315       21.315         13.135
18                           19     24.952       24.952         15.376
19                           20     25.189       25.189         15.522
20                           21     20.707       20.707         12.760
21                           22     18.810       18.810         11.591
22                           23     14.784       14.784          9.109
23                           24     10.526       10.526          6.484
24                           25      7.227        7.227          4.450
25                           26      6.192        6.192          3.812
26                           27      5.889        5.889          3.625
27                           28      5.681        5.681          3.497
28                           29      5.799        5.799          3.570
29                           30      9.496        9.496          5.849
30                           31     17.015       17.015         10.485
31                           32     18.880       18.880         11.635
32                           33     17.674       17.674         10.891
33                           34     16.212       16.212          9.991
34                           35     16.170       16.170          9.965
35                           36     17.547       17.547         10.814
36                           37     18.819       18.819         11.598
37                           38     16.961       16.961         10.452
38                           39     15.279       15.279          9.415
39                           40     14.426       14.426          8.889
40                           41     16.583       16.583         10.218
41                           42     22.052       22.052         13.589
42                           43     26.865       26.865         16.555
43                           44     26.446       26.446         16.297
44                           45     22.044       22.044         13.583
45                           46     19.524       19.524         12.030
46                           47     15.403       15.403          9.489
47                           48     10.740       10.740          6.615
48                           49      7.388        7.388          4.549
49                           50      6.317        6.317          3.889

    Suderdonn  Heide west  Brunsbuttel  itzehoe West  Klixbull Sud  Nielbull  \
0       5.942       5.942        2.971         2.971         4.118     8.237
1       4.402       4.402        2.201         2.201         3.051     6.103
2       3.905       3.905        1.953         1.953         2.708     5.415
3       3.576       3.576        1.788         1.788         2.479     4.959
4       3.378       3.378        1.689         1.689         2.343     4.685
5       3.493       3.493        1.746         1.746         2.422     4.844
6       3.937       3.937        1.968         1.968         2.730     5.460
7       6.121       6.121        3.060         3.060         4.243     8.486
8      10.717      10.717        5.359         5.359         7.428    14.856
9      14.271      14.271        7.136         7.136         9.890    19.781
10     17.084      17.084        8.542         8.542        11.839    23.678
11     18.760      18.760        9.380         9.380        13.000    26.000
12     16.762      16.762        8.381         8.381        11.615    23.231
13     13.016      13.016        6.508         6.508         9.019    18.039
14     10.812      10.812        5.406         5.406         7.493    14.985
15      9.521       9.521        4.761         4.761         6.598    13.196
16     10.023      10.023        5.012         5.012         6.946    13.892
17     13.135      13.135        6.567         6.567         9.102    18.204
18     15.376      15.376        7.688         7.688        10.655    21.310
19     15.522      15.522        7.761         7.761        10.756    21.512
20     12.760      12.760        6.380         6.380         8.842    17.685
21     11.591      11.591        5.795         5.795         8.032    16.064
22      9.109       9.109        4.554         4.554         6.313    12.625
23      6.484       6.484        3.242         3.242         4.494     8.989
24      4.450       4.450        2.225         2.225         3.085     6.170
25      3.812       3.812        1.906         1.906         2.643     5.287
26      3.625       3.625        1.813         1.813         2.514     5.027
27      3.497       3.497        1.749         1.749         2.425     4.850
28      3.570       3.570        1.785         1.785         2.476     4.951
29      5.849       5.849        2.925         2.925         4.054     8.109
30     10.485      10.485        5.242         5.242         7.266    14.531
31     11.635      11.635        5.818         5.818         8.062    16.125
32     10.891      10.891        5.446         5.446         7.547    15.094
33      9.991       9.991        4.995         4.995         6.923    13.846
34      9.965       9.965        4.982         4.982         6.905    13.809
35     10.814      10.814        5.407         5.407         7.493    14.986
36     11.598      11.598        5.799         5.799         8.036    16.073
37     10.452      10.452        5.226         5.226         7.243    14.486
38      9.415       9.415        4.707         4.707         6.524    13.048
39      8.889       8.889        4.444         4.444         6.160    12.320
40     10.218      10.218        5.109         5.109         7.081    14.162
41     13.589      13.589        6.794         6.794         9.416    18.833
42     16.555      16.555        8.278         8.278        11.472    22.944
43     16.297      16.297        8.148         8.148        11.293    22.586
44     13.583      13.583        6.791         6.791         9.413    18.825
45     12.030      12.030        6.015         6.015         8.337    16.674
46      9.489       9.489        4.745         4.745         6.577    13.153
47      6.615       6.615        3.308         3.308         4.585     9.170
48      4.549       4.549        2.274         2.274         3.154     6.307
49      3.889       3.889        1.945         1.945         2.697     5.393

    ...  St lorenz sud  Bad Schwartau west  St lorenz Nord  Strecknitz  \
0   ...          1.239               6.193           2.477       4.954
1   ...          0.918               4.588           1.835       3.670
2   ...          0.814               4.070           1.628       3.256
3   ...          0.745               3.726           1.491       2.981
4   ...          0.704               3.520           1.408       2.816
5   ...          0.728               3.640           1.456       2.912
6   ...          0.820               4.102           1.641       3.282
7   ...          1.276               6.379           2.552       5.103
8   ...          2.234              11.170           4.468       8.936
9   ...          2.975              14.874           5.950      11.899
10  ...          3.561              17.806           7.122      14.244
11  ...          3.910              19.552           7.821      15.641
12  ...          3.494              17.470           6.988      13.976
13  ...          2.713              13.565           5.426      10.852
14  ...          2.254              11.268           4.507       9.015
15  ...          1.985               9.923           3.969       7.938
16  ...          2.089              10.446           4.179       8.357
17  ...          2.738              13.690           5.476      10.952
18  ...          3.205              16.026           6.410      12.821
19  ...          3.236              16.178           6.471      12.942
20  ...          2.660              13.299           5.320      10.639
21  ...          2.416              12.080           4.832       9.664
22  ...          1.899               9.493           3.797       7.594
23  ...          1.352               6.758           2.703       5.406
24  ...          0.927               4.637           1.855       3.710
25  ...          0.795               3.973           1.589       3.178
26  ...          0.756               3.778           1.511       3.022
27  ...          0.729               3.644           1.458       2.915
28  ...          0.744               3.721           1.488       2.976
29  ...          1.219               6.096           2.438       4.877
30  ...          2.185              10.927           4.371       8.742
31  ...          2.425              12.127           4.851       9.701
32  ...          2.270              11.352           4.541       9.081
33  ...          2.083              10.413           4.165       8.330
34  ...          2.077              10.385           4.154       8.308
35  ...          2.254              11.270           4.508       9.016
36  ...          2.418              12.088           4.835       9.670
37  ...          2.179              10.893           4.357       8.715
38  ...          1.962               9.812           3.925       7.850
39  ...          1.853               9.264           3.706       7.411
40  ...          2.130              10.650           4.260       8.520
41  ...          2.833              14.163           5.665      11.330
42  ...          3.451              17.255           6.902      13.804
43  ...          3.397              16.985           6.794      13.588
44  ...          2.831              14.156           5.662      11.325
45  ...          2.508              12.538           5.015      10.030
46  ...          1.978               9.890           3.956       7.912
47  ...          1.379               6.894           2.758       5.515
48  ...          0.948               4.740           1.896       3.792
49  ...          0.811               4.053           1.621       3.242

    lubeck Genin  Bad Oldesloe  Genin sud  Marli  Einfeld  Neumunster nord
0          4.954         2.212      2.212  1.106    0.300             0.300
1          3.670         1.643      1.643  0.821    0.224             0.224
2          3.256         1.463      1.463  0.732    0.200             0.200
3          2.981         1.344      1.344  0.672    0.185             0.185
4          2.816         1.273      1.273  0.636    0.175             0.175
5          2.912         1.316      1.316  0.658    0.181             0.181
6          3.282         1.482      1.482  0.741    0.204             0.204
7          5.103         2.287      2.287  1.144    0.312             0.312
8          8.936         3.986      3.986  1.993    0.541             0.541
9         11.899         5.301      5.301  2.651    0.718             0.718
10        14.244         6.340      6.340  3.170    0.858             0.858
11        15.641         6.957      6.957  3.479    0.941             0.941
12        13.976         6.215      6.215  3.108    0.841             0.841
13        10.852         4.827      4.827  2.413    0.653             0.653
14         9.015         4.012      4.012  2.006    0.543             0.543
15         7.938         3.534      3.534  1.767    0.479             0.479
16         8.357         3.721      3.721  1.860    0.504             0.504
17        10.952         4.870      4.870  2.435    0.659             0.659
18        12.821         5.699      5.699  2.849    0.770             0.770
19        12.942         5.754      5.754  2.877    0.778             0.778
20        10.639         4.732      4.732  2.366    0.640             0.640
21         9.664         4.301      4.301  2.151    0.582             0.582
22         7.594         3.386      3.386  1.693    0.459             0.459
23         5.406         2.417      2.417  1.208    0.329             0.329
24         3.710         1.668      1.668  0.834    0.228             0.228
25         3.178         1.432      1.432  0.716    0.196             0.196
26         3.022         1.363      1.363  0.682    0.187             0.187
27         2.915         1.315      1.315  0.658    0.181             0.181
28         2.976         1.341      1.341  0.671    0.184             0.184
29         4.877         2.181      2.181  1.091    0.297             0.297
30         8.742         3.890      3.890  1.945    0.527             0.527
31         9.701         4.311      4.311  2.155    0.583             0.583
32         9.081         4.037      4.037  2.018    0.546             0.546
33         8.330         3.702      3.702  1.851    0.500             0.500
34         8.308         3.692      3.692  1.846    0.499             0.499
35         9.016         4.007      4.007  2.003    0.541             0.541
36         9.670         4.296      4.296  2.148    0.580             0.580
37         8.715         3.876      3.876  1.938    0.524             0.524
38         7.850         3.494      3.494  1.747    0.473             0.473
39         7.411         3.300      3.300  1.650    0.447             0.447
40         8.520         3.789      3.789  1.895    0.513             0.513
41        11.330         5.037      5.037  2.518    0.681             0.681
42        13.804         6.135      6.135  3.067    0.829             0.829
43        13.588         6.043      6.043  3.022    0.817             0.817
44        11.325         5.041      5.041  2.521    0.683             0.683
45        10.030         4.467      4.467  2.233    0.605             0.605
46         7.912         3.531      3.531  1.765    0.479             0.479
47         5.515         2.468      2.468  1.234    0.336             0.336
48         3.792         1.706      1.706  0.853    0.234             0.234
49         3.242         1.461      1.461  0.731    0.200             0.200

[50 rows x 38 columns]

In [6]:
# read CSV file electrodeHeater
df_electrodeHeater = data_frame("timeseriesdata/ts_HH_loadData_2030_electrodeHeater.csv", sep=";")
df_electrodeHeater = df_electrodeHeater.applymap(lambda x: x.replace(".", "") if isinstance(x, str) else x)
print(df_electrodeHeater.head(50))

    electrodeHeater  Handewitt  Schuby west  Uw Husum Nord  Suderdonn  \
0                 1        0.0          0.0            0.0        0.0
1                 2        0.0          0.0            0.0        0.0
2                 3        0.0          0.0            0.0        0.0
3                 4        0.0          0.0            0.0        0.0
4                 5        0.0          0.0            0.0        0.0
5                 6        0.0          0.0            0.0        0.0
6                 7        0.0          0.0            0.0        0.0
7                 8        0.0          0.0            0.0        0.0
8                 9        0.0          0.0            0.0        0.0
9                10        0.0          0.0            0.0        0.0
10               11        0.0          0.0            0.0        0.0
11               12        0.0          0.0            0.0        0.0
12               13        0.0          0.0            0.0        0.0
13               14        0.0          0.0            0.0        0.0
14               15        0.0          0.0            0.0        0.0
15               16        0.0          0.0            0.0        0.0
16               17        0.0          0.0            0.0        0.0
17               18        0.0          0.0            0.0        0.0
18               19        0.0          0.0            0.0        0.0
19               20        0.0          0.0            0.0        0.0
20               21        0.0          0.0            0.0        0.0
21               22        0.0          0.0            0.0        0.0
22               23        0.0          0.0            0.0        0.0
23               24        0.0          0.0            0.0        0.0
24               25        0.0          0.0            0.0        0.0
25               26        0.0          0.0            0.0        0.0
26               27        0.0          0.0            0.0        0.0
27               28        0.0          0.0            0.0        0.0
28               29        0.0          0.0            0.0        0.0
29               30        0.0          0.0            0.0        0.0
30               31        0.0          0.0            0.0        0.0
31               32        0.0          0.0            0.0        0.0
32               33        0.0          0.0            0.0        0.0
33               34        0.0          0.0            0.0        0.0
34               35        0.0          0.0            0.0        0.0
35               36        0.0          0.0            0.0        0.0
36               37        0.0          0.0            0.0        0.0
37               38        0.0          0.0            0.0        0.0
38               39        0.0          0.0            0.0        0.0
39               40        0.0          0.0            0.0        0.0
40               41        0.0          0.0            0.0        0.0
41               42        0.0          0.0            0.0        0.0
42               43        0.0          0.0            0.0        0.0
43               44        0.0          0.0            0.0        0.0
44               45        0.0          0.0            0.0        0.0
45               46        0.0          0.0            0.0        0.0
46               47        0.0          0.0            0.0        0.0
47               48        0.0          0.0            0.0        0.0
48               49        0.0          0.0            0.0        0.0
49               50        0.0          0.0            0.0        0.0

    Heide west  Brunsbuttel  itzehoe West  Klixbull Sud  Nielbull  ...  \
0          0.0          0.0           0.0           0.0       0.0  ...
1          0.0          0.0           0.0           0.0       0.0  ...
2          0.0          0.0           0.0           0.0       0.0  ...
3          0.0          0.0           0.0           0.0       0.0  ...
4          0.0          0.0           0.0           0.0       0.0  ...
5          0.0          0.0           0.0           0.0       0.0  ...
6          0.0          0.0           0.0           0.0       0.0  ...
7          0.0          0.0           0.0           0.0       0.0  ...
8          0.0          0.0           0.0           0.0       0.0  ...
9          0.0          0.0           0.0           0.0       0.0  ...
10         0.0          0.0           0.0           0.0       0.0  ...
11         0.0          0.0           0.0           0.0       0.0  ...
12         0.0          0.0           0.0           0.0       0.0  ...
13         0.0          0.0           0.0           0.0       0.0  ...
14         0.0          0.0           0.0           0.0       0.0  ...
15         0.0          0.0           0.0           0.0       0.0  ...
16         0.0          0.0           0.0           0.0       0.0  ...
17         0.0          0.0           0.0           0.0       0.0  ...
18         0.0          0.0           0.0           0.0       0.0  ...
19         0.0          0.0           0.0           0.0       0.0  ...
20         0.0          0.0           0.0           0.0       0.0  ...
21         0.0          0.0           0.0           0.0       0.0  ...
22         0.0          0.0           0.0           0.0       0.0  ...
23         0.0          0.0           0.0           0.0       0.0  ...
24         0.0          0.0           0.0           0.0       0.0  ...
25         0.0          0.0           0.0           0.0       0.0  ...
26         0.0          0.0           0.0           0.0       0.0  ...
27         0.0          0.0           0.0           0.0       0.0  ...
28         0.0          0.0           0.0           0.0       0.0  ...
29         0.0          0.0           0.0           0.0       0.0  ...
30         0.0          0.0           0.0           0.0       0.0  ...
31         0.0          0.0           0.0           0.0       0.0  ...
32         0.0          0.0           0.0           0.0       0.0  ...
33         0.0          0.0           0.0           0.0       0.0  ...
34         0.0          0.0           0.0           0.0       0.0  ...
35         0.0          0.0           0.0           0.0       0.0  ...
36         0.0          0.0           0.0           0.0       0.0  ...
37         0.0          0.0           0.0           0.0       0.0  ...
38         0.0          0.0           0.0           0.0       0.0  ...
39         0.0          0.0           0.0           0.0       0.0  ...
40         0.0          0.0           0.0           0.0       0.0  ...
41         0.0          0.0           0.0           0.0       0.0  ...
42         0.0          0.0           0.0           0.0       0.0  ...
43         0.0          0.0           0.0           0.0       0.0  ...
44         0.0          0.0           0.0           0.0       0.0  ...
45         0.0          0.0           0.0           0.0       0.0  ...
46         0.0          0.0           0.0           0.0       0.0  ...
47         0.0          0.0           0.0           0.0       0.0  ...
48         0.0          0.0           0.0           0.0       0.0  ...
49         0.0          0.0           0.0           0.0       0.0  ...

    St lorenz sud  Bad Schwartau west  St lorenz Nord  Strecknitz  \
0             0.0                 0.0             0.0         0.0
1             0.0                 0.0             0.0         0.0
2             0.0                 0.0             0.0         0.0
3             0.0                 0.0             0.0         0.0
4             0.0                 0.0             0.0         0.0
5             0.0                 0.0             0.0         0.0
6             0.0                 0.0             0.0         0.0
7             0.0                 0.0             0.0         0.0
8             0.0                 0.0             0.0         0.0
9             0.0                 0.0             0.0         0.0
10            0.0                 0.0             0.0         0.0
11            0.0                 0.0             0.0         0.0
12            0.0                 0.0             0.0         0.0
13            0.0                 0.0             0.0         0.0
14            0.0                 0.0             0.0         0.0
15            0.0                 0.0             0.0         0.0
16            0.0                 0.0             0.0         0.0
17            0.0                 0.0             0.0         0.0
18            0.0                 0.0             0.0         0.0
19            0.0                 0.0             0.0         0.0
20            0.0                 0.0             0.0         0.0
21            0.0                 0.0             0.0         0.0
22            0.0                 0.0             0.0         0.0
23            0.0                 0.0             0.0         0.0
24            0.0                 0.0             0.0         0.0
25            0.0                 0.0             0.0         0.0
26            0.0                 0.0             0.0         0.0
27            0.0                 0.0             0.0         0.0
28            0.0                 0.0             0.0         0.0
29            0.0                 0.0             0.0         0.0
30            0.0                 0.0             0.0         0.0
31            0.0                 0.0             0.0         0.0
32            0.0                 0.0             0.0         0.0
33            0.0                 0.0             0.0         0.0
34            0.0                 0.0             0.0         0.0
35            0.0                 0.0             0.0         0.0
36            0.0                 0.0             0.0         0.0
37            0.0                 0.0             0.0         0.0
38            0.0                 0.0             0.0         0.0
39            0.0                 0.0             0.0         0.0
40            0.0                 0.0             0.0         0.0
41            0.0                 0.0             0.0         0.0
42            0.0                 0.0             0.0         0.0
43            0.0                 0.0             0.0         0.0
44            0.0                 0.0             0.0         0.0
45            0.0                 0.0             0.0         0.0
46            0.0                 0.0             0.0         0.0
47            0.0                 0.0             0.0         0.0
48            0.0                 0.0             0.0         0.0
49            0.0                 0.0             0.0         0.0

    lubeck Genin  Bad Oldesloe  Genin sud  Marli  Einfeld  Neumunster nord
0            0.0           0.0        0.0    0.0      0.0               0.0
1            0.0           0.0        0.0    0.0      0.0               0.0
2            0.0           0.0        0.0    0.0      0.0               0.0
3            0.0           0.0        0.0    0.0      0.0               0.0
4            0.0           0.0        0.0    0.0      0.0               0.0
5            0.0           0.0        0.0    0.0      0.0               0.0
6            0.0           0.0        0.0    0.0      0.0               0.0
7            0.0           0.0        0.0    0.0      0.0               0.0
8            0.0           0.0        0.0    0.0      0.0               0.0
9            0.0           0.0        0.0    0.0      0.0               0.0
10           0.0           0.0        0.0    0.0      0.0               0.0
11           0.0           0.0        0.0    0.0      0.0               0.0
12           0.0           0.0        0.0    0.0      0.0               0.0
13           0.0           0.0        0.0    0.0      0.0               0.0
14           0.0           0.0        0.0    0.0      0.0               0.0
15           0.0           0.0        0.0    0.0      0.0               0.0
16           0.0           0.0        0.0    0.0      0.0               0.0
17           0.0           0.0        0.0    0.0      0.0               0.0
18           0.0           0.0        0.0    0.0      0.0               0.0
19           0.0           0.0        0.0    0.0      0.0               0.0
20           0.0           0.0        0.0    0.0      0.0               0.0
21           0.0           0.0        0.0    0.0      0.0               0.0
22           0.0           0.0        0.0    0.0      0.0               0.0
23           0.0           0.0        0.0    0.0      0.0               0.0
24           0.0           0.0        0.0    0.0      0.0               0.0
25           0.0           0.0        0.0    0.0      0.0               0.0
26           0.0           0.0        0.0    0.0      0.0               0.0
27           0.0           0.0        0.0    0.0      0.0               0.0
28           0.0           0.0        0.0    0.0      0.0               0.0
29           0.0           0.0        0.0    0.0      0.0               0.0
30           0.0           0.0        0.0    0.0      0.0               0.0
31           0.0           0.0        0.0    0.0      0.0               0.0
32           0.0           0.0        0.0    0.0      0.0               0.0
33           0.0           0.0        0.0    0.0      0.0               0.0
34           0.0           0.0        0.0    0.0      0.0               0.0
35           0.0           0.0        0.0    0.0      0.0               0.0
36           0.0           0.0        0.0    0.0      0.0               0.0
37           0.0           0.0        0.0    0.0      0.0               0.0
38           0.0           0.0        0.0    0.0      0.0               0.0
39           0.0           0.0        0.0    0.0      0.0               0.0
40           0.0           0.0        0.0    0.0      0.0               0.0
41           0.0           0.0        0.0    0.0      0.0               0.0
42           0.0           0.0        0.0    0.0      0.0               0.0
43           0.0           0.0        0.0    0.0      0.0               0.0
44           0.0           0.0        0.0    0.0      0.0               0.0
45           0.0           0.0        0.0    0.0      0.0               0.0
46           0.0           0.0        0.0    0.0      0.0               0.0
47           0.0           0.0        0.0    0.0      0.0               0.0
48           0.0           0.0        0.0    0.0      0.0               0.0
49           0.0           0.0        0.0    0.0      0.0               0.0

[50 rows x 38 columns]

C:\Users\user\AppData\Local\Temp\ipykernel_10364\3334854735.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_electrodeHeater = df_electrodeHeater.applymap(lambda x: x.replace(".", "") if isinstance(x, str) else x)

In [7]:
# List columns for wind
df_wind.columns.tolist()
df_wind.head(100)

,onshoreWind,Handewitt,Schuby west,Uw Husum Nord,Suderdonn,Heide west,Brunsbuttel,itzehoe West,Klixbull Sud,Nielbull,Lubeck,Siems,Jardelund,Uw Weesby,Kiel West,Breklum,Horstedt,Oldersbek,Rendsburg Nord
0,1,20.520,8.577,0,6.960,0,0,0.370,4.215,0,0,0,1.556,0,0,0,0,7.862,1.317
1,2,32.611,11.789,0,9.581,0,0,0.504,5.546,0,0,0,2.634,0,0,0,0,12.552,2.993
2,3,43.370,17.905,0,16.296,0,0,1.143,8.985,0,0,0,5.866,0,0,0,0,25.149,4.310
3,4,43.370,17.134,0,14.637,0,0,0.840,8.652,0,0,0,5.267,0,0,0,0,26.287,6.824
4,5,43.370,17.644,0,14.877,0,0,0.840,8.430,0,0,0,4.669,0,0,0,0,24.012,5.866
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,48.916,22.211,0,19.928,0,0,2.622,9.761,0,0,0,10.295,0,0,0,0,32.297,10.295
96,97,48.361,21.581,0,18.783,0,0,2.925,9.317,0,0,0,10.774,0,0,0,0,32.143,10.654
97,98,48.805,22.100,0,19.817,0,0,2.858,9.761,0,0,0,10.774,0,0,0,0,32.936,10.654
98,99,47.252,21.118,0,19.014,0,0,2.925,9.428,0,0,0,10.774,0,0,0,0,32.512,10.774
99,100,39.377,19.565,0,17.178,0,0,2.858,8.319,0,0,0,10.415,0,0,0,0,28.637,9.816

In [8]:
# List columns for photovoltaics
df_photovoltaics.columns.tolist()
df_photovoltaics.head(100)

,photovoltaics,Handewitt,Schuby west,Uw Husum Nord,Suderdonn,Heide west,Brunsbuttel,itzehoe West,Klixbull Sud,Nielbull,...,St lorenz sud,Bad Schwartau west,St lorenz Nord,Strecknitz,lubeck Genin,Bad Oldesloe,Genin sud,Marli,Einfeld,Neumunster nord
0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
96,97,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,99,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
# List columns for conventionalLoads
df_conventionalLoads.columns.tolist()
df_conventionalLoads.head(100)

,conventionalLoad_households,Handewitt,Schuby west,Uw Husum Nord,Suderdonn,Heide west,Brunsbuttel,itzehoe West,Klixbull Sud,Nielbull,...,St lorenz sud,Bad Schwartau west,St lorenz Nord,Strecknitz,lubeck Genin,Bad Oldesloe,Genin sud,Marli,Einfeld,Neumunster nord
0,1,9.646,9.646,5.942,5.942,5.942,2.971,2.971,4.118,8.237,...,1.239,6.193,2.477,4.954,4.954,2.212,2.212,1.106,0.300,0.300
1,2,7.147,7.147,4.402,4.402,4.402,2.201,2.201,3.051,6.103,...,0.918,4.588,1.835,3.670,3.670,1.643,1.643,0.821,0.224,0.224
2,3,6.342,6.342,3.905,3.905,3.905,1.953,1.953,2.708,5.415,...,0.814,4.070,1.628,3.256,3.256,1.463,1.463,0.732,0.200,0.200
3,4,5.809,5.809,3.576,3.576,3.576,1.788,1.788,2.479,4.959,...,0.745,3.726,1.491,2.981,2.981,1.344,1.344,0.672,0.185,0.185
4,5,5.488,5.488,3.378,3.378,3.378,1.689,1.689,2.343,4.685,...,0.704,3.520,1.408,2.816,2.816,1.273,1.273,0.636,0.175,0.175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,10.987,10.987,6.767,6.767,6.767,3.383,3.383,4.691,9.381,...,1.410,7.052,2.821,5.641,5.641,2.527,2.527,1.263,0.344,0.344
96,97,7.506,7.506,4.622,4.622,4.622,2.311,2.311,3.204,6.409,...,0.963,4.816,1.926,3.853,3.853,1.734,1.734,0.867,0.237,0.237
97,98,6.403,6.403,3.942,3.942,3.942,1.971,1.971,2.733,5.466,...,0.822,4.108,1.643,3.286,3.286,1.482,1.482,0.741,0.204,0.204
98,99,6.049,6.049,3.724,3.724,3.724,1.862,1.862,2.582,5.165,...,0.776,3.880,1.552,3.104,3.104,1.401,1.401,0.701,0.193,0.193
99,100,5.820,5.820,3.582,3.582,3.582,1.791,1.791,2.484,4.969,...,0.747,3.733,1.493,2.986,2.986,1.351,1.351,0.675,0.186,0.186

In [10]:
# List columns for electrodeHeater
df_electrodeHeater.columns.tolist()
df_electrodeHeater.head(20)

,electrodeHeater,Handewitt,Schuby west,Uw Husum Nord,Suderdonn,Heide west,Brunsbuttel,itzehoe West,Klixbull Sud,Nielbull,...,St lorenz sud,Bad Schwartau west,St lorenz Nord,Strecknitz,lubeck Genin,Bad Oldesloe,Genin sud,Marli,Einfeld,Neumunster nord
0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
df_wind.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   onshoreWind     8760 non-null   int64
 1   Handewitt       8760 non-null   float64
 2   Schuby west     8760 non-null   float64
 3   Uw Husum Nord   8760 non-null   int64
 4   Suderdonn       8760 non-null   float64
 5   Heide west      8760 non-null   int64
 6   Brunsbuttel     8760 non-null   int64
 7   itzehoe West    8760 non-null   float64
 8   Klixbull Sud    8760 non-null   float64
 9   Nielbull        8760 non-null   int64
 10  Lubeck          8760 non-null   int64
 11  Siems           8760 non-null   int64
 12  Jardelund       8760 non-null   float64
 13  Uw Weesby       8760 non-null   int64
 14  Kiel West       8760 non-null   int64
 15  Breklum         8760 non-null   int64
 16  Horstedt        8760 non-null   int64
 17  Oldersbek       8760 non-null   float64
 18  Rendsburg Nord  8760 non-null   float64
dtypes: float64(8), int64(11)
memory usage: 1.3 MB

In [12]:
df_conventionalLoads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   conventionalLoad_households  8760 non-null   int64
 1   Handewitt                    8760 non-null   float64
 2   Schuby west                  8760 non-null   float64
 3   Uw Husum Nord                8760 non-null   float64
 4   Suderdonn                    8760 non-null   float64
 5   Heide west                   8760 non-null   float64
 6   Brunsbuttel                  8760 non-null   float64
 7   itzehoe West                 8760 non-null   float64
 8   Klixbull Sud                 8760 non-null   float64
 9   Nielbull                     8760 non-null   float64
 10  Lubeck                       8760 non-null   float64
 11  Siems                        8760 non-null   float64
 12  Jardelund                    8760 non-null   float64
 13  Uw Weesby                    8760 non-null   float64
 14  Kiel West                    8760 non-null   float64
 15  Breklum                      8760 non-null   float64
 16  Horstedt                     8760 non-null   float64
 17  Oldersbek                    8760 non-null   float64
 18  Rendsburg Nord               8760 non-null   float64
 19  Schacht                      8760 non-null   float64
 20  Rendsburg Mitte              8760 non-null   float64
 21  Uw Nortorf                   8760 non-null   float64
 22  Bornhoved                    8760 non-null   float64
 23  Bad Segeberg                 8760 non-null   float64
 24  Wahlstedt                    8760 non-null   float64
 25  Geschendorf                  8760 non-null   float64
 26  Schlaltanlage Lubeck Sud     8760 non-null   float64
 27  Lubeck Zentrum               8760 non-null   float64
 28  St lorenz sud                8760 non-null   float64
 29  Bad Schwartau west           8760 non-null   float64
 30  St lorenz Nord               8760 non-null   float64
 31  Strecknitz                   8760 non-null   float64
 32  lubeck Genin                 8760 non-null   float64
 33  Bad Oldesloe                 8760 non-null   float64
 34  Genin sud                    8760 non-null   float64
 35  Marli                        8760 non-null   float64
 36  Einfeld                      8760 non-null   float64
 37  Neumunster nord              8760 non-null   float64
dtypes: float64(37), int64(1)
memory usage: 2.5 MB

In [13]:
df_electrodeHeater.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   electrodeHeater           8760 non-null   int64
 1   Handewitt                 8760 non-null   float64
 2   Schuby west               8760 non-null   float64
 3   Uw Husum Nord             8760 non-null   float64
 4   Suderdonn                 8760 non-null   float64
 5   Heide west                8760 non-null   float64
 6   Brunsbuttel               8760 non-null   float64
 7   itzehoe West              8760 non-null   float64
 8   Klixbull Sud              8760 non-null   float64
 9   Nielbull                  8760 non-null   float64
 10  Lubeck                    8760 non-null   float64
 11  Siems                     8760 non-null   float64
 12  Jardelund                 8760 non-null   float64
 13  Uw Weesby                 8760 non-null   float64
 14  Kiel West                 8760 non-null   float64
 15  Breklum                   8760 non-null   float64
 16  Horstedt                  8760 non-null   float64
 17  Oldersbek                 8760 non-null   float64
 18  Rendsburg Nord            8760 non-null   float64
 19  Schacht                   8760 non-null   float64
 20  Rendsburg Mitte           8760 non-null   float64
 21  Uw Nortorf                8760 non-null   float64
 22  Bornhoved                 8760 non-null   float64
 23  Bad Segeberg              8760 non-null   float64
 24  Wahlstedt                 8760 non-null   float64
 25  Geschendorf               8760 non-null   float64
 26  Schlaltanlage Lubeck Sud  8760 non-null   float64
 27  Lubeck Zentrum            8760 non-null   float64
 28  St lorenz sud             8760 non-null   float64
 29  Bad Schwartau west        8760 non-null   float64
 30  St lorenz Nord            8760 non-null   float64
 31  Strecknitz                8760 non-null   float64
 32  lubeck Genin              8760 non-null   float64
 33  Bad Oldesloe              8760 non-null   float64
 34  Genin sud                 8760 non-null   float64
 35  Marli                     8760 non-null   float64
 36  Einfeld                   8760 non-null   float64
 37  Neumunster nord           8760 non-null   float64
dtypes: float64(37), int64(1)
memory usage: 2.5 MB

In [14]:
df_photovoltaics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   photovoltaics             8760 non-null   int64
 1   Handewitt                 8760 non-null   float64
 2   Schuby west               8760 non-null   float64
 3   Uw Husum Nord             8760 non-null   float64
 4   Suderdonn                 8760 non-null   float64
 5   Heide west                8760 non-null   float64
 6   Brunsbuttel               8760 non-null   float64
 7   itzehoe West              8760 non-null   float64
 8   Klixbull Sud              8760 non-null   float64
 9   Nielbull                  8760 non-null   float64
 10  Lubeck                    8760 non-null   float64
 11  Siems                     8760 non-null   float64
 12  Jardelund                 8760 non-null   float64
 13  Uw Weesby                 8760 non-null   float64
 14  Kiel West                 8760 non-null   float64
 15  Breklum                   8760 non-null   float64
 16  Horstedt                  8760 non-null   float64
 17  Oldersbek                 8760 non-null   float64
 18  Rendsburg Nord            8760 non-null   float64
 19  Schacht                   8760 non-null   float64
 20  Rendsburg Mitte           8760 non-null   float64
 21  Uw Nortorf                8760 non-null   float64
 22  Bornhoved                 8760 non-null   float64
 23  Bad Segeberg              8760 non-null   float64
 24  Wahlstedt                 8760 non-null   float64
 25  Geschendorf               8760 non-null   float64
 26  Schlaltanlage Lubeck Sud  8760 non-null   float64
 27  Lubeck Zentrum            8760 non-null   float64
 28  St lorenz sud             8760 non-null   float64
 29  Bad Schwartau west        8760 non-null   float64
 30  St lorenz Nord            8760 non-null   float64
 31  Strecknitz                8760 non-null   float64
 32  lubeck Genin              8760 non-null   float64
 33  Bad Oldesloe              8760 non-null   float64
 34  Genin sud                 8760 non-null   float64
 35  Marli                     8760 non-null   float64
 36  Einfeld                   8760 non-null   float64
 37  Neumunster nord           8760 non-null   float64
dtypes: float64(37), int64(1)
memory usage: 2.5 MB

In [15]:
df_wind.describe().T

,count,mean,std,min,25%,50%,75%,max
onshoreWind,8760.0,4380.500000,2528.938512,1.0,2190.750,4380.5000,6570.25000,8760.000
Handewitt,8760.0,22.853201,15.945955,0.0,7.210,22.6280,37.49100,49.360
Schuby west,8760.0,9.128762,6.724605,0.0,2.738,8.5345,14.88650,22.444
Uw Husum Nord,8760.0,0.000000,0.000000,0.0,0.000,0.0000,0.00000,0.000
Suderdonn,8760.0,7.716517,5.909666,0.0,2.160,6.9285,12.58800,19.928
Heide west,8760.0,0.000000,0.000000,0.0,0.000,0.0000,0.00000,0.000
Brunsbuttel,8760.0,0.000000,0.000000,0.0,0.000,0.0000,0.00000,0.000
itzehoe West,8760.0,0.703007,0.694662,0.0,0.168,0.4710,1.04200,2.925
Klixbull Sud,8760.0,4.415889,3.162759,0.0,1.331,4.2150,7.32100,9.872
Nielbull,8760.0,0.000000,0.000000,0.0,0.000,0.0000,0.00000,0.000
Lubeck,8760.0,0.000000,0.000000,0.0,0.000,0.0000,0.00000,0.000
Siems,8760.0,0.000000,0.000000,0.0,0.000,0.0000,0.00000,0.000
Jardelund,8760.0,3.583010,2.994680,0.0,0.958,2.8730,5.62600,10.774
Uw Weesby,8760.0,0.000000,0.000000,0.0,0.000,0.0000,0.00000,0.000
Kiel West,8760.0,0.000000,0.000000,0.0,0.000,0.0000,0.00000,0.000
Breklum,8760.0,0.000000,0.000000,0.0,0.000,0.0000,0.00000,0.000
Horstedt,8760.0,0.000000,0.000000,0.0,0.000,0.0000,0.00000,0.000
Oldersbek,8760.0,13.536919,9.986367,0.0,4.147,12.5545,22.09975,32.956
Rendsburg Nord,8760.0,3.620609,2.948734,0.0,1.077,2.9930,5.74600,10.774

In [16]:
df_photovoltaics.describe().T

,count,mean,std,min,25%,50%,75%,max
photovoltaics,8760.0,4380.500000,2528.938512,1.0,2190.75,4380.500,6570.25000,8760.000
Handewitt,8760.0,2.079133,3.543119,0.0,0.00,0.017,2.50525,16.047
Schuby west,8760.0,0.493068,0.840886,0.0,0.00,0.004,0.59125,3.868
Uw Husum Nord,8760.0,0.493068,0.840886,0.0,0.00,0.004,0.59125,3.868
Suderdonn,8760.0,0.493030,0.840793,0.0,0.00,0.004,0.59125,3.868
Heide west,8760.0,0.415575,0.710925,0.0,0.00,0.003,0.49425,3.298
Brunsbuttel,8760.0,0.415575,0.710925,0.0,0.00,0.003,0.49425,3.298
itzehoe West,8760.0,0.415575,0.710925,0.0,0.00,0.003,0.49425,3.298
Klixbull Sud,8760.0,0.593006,1.011014,0.0,0.00,0.005,0.71325,4.705
Nielbull,8760.0,0.593006,1.011014,0.0,0.00,0.005,0.71325,4.705
Lubeck,8760.0,0.914955,1.552327,0.0,0.00,0.008,1.13900,7.243
Siems,8760.0,0.641798,1.097667,0.0,0.00,0.005,0.76600,5.100
Jardelund,8760.0,0.641798,1.097667,0.0,0.00,0.005,0.76600,5.100
Uw Weesby,8760.0,1.271260,2.161915,0.0,0.00,0.010,1.54475,9.775
Kiel West,8760.0,0.644701,1.098942,0.0,0.00,0.005,0.78225,4.979
Breklum,8760.0,0.644701,1.098942,0.0,0.00,0.005,0.78225,4.979
Horstedt,8760.0,0.644701,1.098942,0.0,0.00,0.005,0.78225,4.979
Oldersbek,8760.0,1.263224,2.165956,0.0,0.00,0.010,1.49125,10.027
Rendsburg Nord,8760.0,1.263143,2.165817,0.0,0.00,0.010,1.49125,10.026
Schacht,8760.0,0.634502,1.081436,0.0,0.00,0.005,0.76600,5.008
Rendsburg Mitte,8760.0,0.634502,1.081436,0.0,0.00,0.005,0.76600,5.008
Uw Nortorf,8760.0,0.421001,0.721831,0.0,0.00,0.003,0.49700,3.342
Bornhoved,8760.0,0.421001,0.721831,0.0,0.00,0.003,0.49700,3.342
Bad Segeberg,8760.0,0.421001,0.721831,0.0,0.00,0.003,0.49700,3.342
Wahlstedt,8760.0,0.252606,0.433125,0.0,0.00,0.002,0.29800,2.005
Geschendorf,8760.0,0.252606,0.433125,0.0,0.00,0.002,0.29800,2.005
Schlaltanlage Lubeck Sud,8760.0,0.252606,0.433125,0.0,0.00,0.002,0.29800,2.005
Lubeck Zentrum,8760.0,0.252606,0.433125,0.0,0.00,0.002,0.29800,2.005
St lorenz sud,8760.0,0.252606,0.433125,0.0,0.00,0.002,0.29800,2.005
Bad Schwartau west,8760.0,1.445932,2.450187,0.0,0.00,0.012,1.78275,11.079
St lorenz Nord,8760.0,0.421008,0.721843,0.0,0.00,0.003,0.49700,3.342
Strecknitz,8760.0,0.421008,0.721843,0.0,0.00,0.003,0.49700,3.342
lubeck Genin,8760.0,0.421008,0.721843,0.0,0.00,0.003,0.49700,3.342
Bad Oldesloe,8760.0,0.773425,1.310560,0.0,0.00,0.006,0.95000,5.872
Genin sud,8760.0,0.773425,1.310560,0.0,0.00,0.006,0.95000,5.872
Marli,8760.0,0.113675,0.194910,0.0,0.00,0.001,0.13400,0.902
Einfeld,8760.0,0.113675,0.194910,0.0,0.00,0.001,0.13400,0.902
Neumunster nord,8760.0,0.113675,0.194910,0.0,0.00,0.001,0.13400,0.902

In [17]:
df_conventionalLoads.describe().T

,count,mean,std,min,25%,50%,75%,max
conventionalLoad_households,8760.0,4380.500000,2528.938512,1.000,2190.75000,4380.5000,6570.25000,8760.000
Handewitt,8760.0,15.997887,6.385029,2.439,10.18550,17.1320,20.43525,35.139
Schuby west,8760.0,15.997887,6.385029,2.439,10.18550,17.1320,20.43525,35.139
Uw Husum Nord,8760.0,9.857877,3.935498,1.502,6.27450,10.5580,12.59400,21.657
Suderdonn,8760.0,9.857877,3.935498,1.502,6.27450,10.5580,12.59400,21.657
Heide west,8760.0,9.857877,3.935498,1.502,6.27450,10.5580,12.59400,21.657
Brunsbuttel,8760.0,4.928937,1.967751,0.751,3.13675,5.2790,6.29700,10.829
itzehoe West,8760.0,4.928937,1.967751,0.751,3.13675,5.2790,6.29700,10.829
Klixbull Sud,8760.0,6.831245,2.726713,1.041,4.34875,7.3155,8.72625,15.006
Nielbull,8760.0,13.662483,5.453428,2.082,8.69750,14.6320,17.45300,30.011
Lubeck,8760.0,13.662483,5.453428,2.082,8.69750,14.6320,17.45300,30.011
Siems,8760.0,3.023674,1.206702,0.461,1.92500,3.2380,3.86200,6.641
Jardelund,8760.0,3.023674,1.206702,0.461,1.92500,3.2380,3.86200,6.641
Uw Weesby,8760.0,12.094722,4.826819,1.844,7.70175,12.9515,15.44825,26.564
Kiel West,8760.0,12.094722,4.826819,1.844,7.70175,12.9515,15.44825,26.564
Breklum,8760.0,3.824866,1.526922,0.583,2.43475,4.0970,4.88600,8.403
Horstedt,8760.0,3.824866,1.526922,0.583,2.43475,4.0970,4.88600,8.403
Oldersbek,8760.0,3.824866,1.526922,0.583,2.43475,4.0970,4.88600,8.403
Rendsburg Nord,8760.0,3.824866,1.526922,0.583,2.43475,4.0970,4.88600,8.403
Schacht,8760.0,3.824866,1.526922,0.583,2.43475,4.0970,4.88600,8.403
Rendsburg Mitte,8760.0,3.824866,1.526922,0.583,2.43475,4.0970,4.88600,8.403
Uw Nortorf,8760.0,3.824866,1.526922,0.583,2.43475,4.0970,4.88600,8.403
Bornhoved,8760.0,3.824866,1.526922,0.583,2.43475,4.0970,4.88600,8.403
Bad Segeberg,8760.0,3.824866,1.526922,0.583,2.43475,4.0970,4.88600,8.403
Wahlstedt,8760.0,3.824866,1.526922,0.583,2.43475,4.0970,4.88600,8.403
Geschendorf,8760.0,4.109674,1.640756,0.626,2.61575,4.4015,5.25100,9.029
Schlaltanlage Lubeck Sud,8760.0,2.054835,0.820377,0.313,1.30775,2.2010,2.62500,4.515
Lubeck Zentrum,8760.0,2.054835,0.820377,0.313,1.30775,2.2010,2.62500,4.515
St lorenz sud,8760.0,2.054835,0.820377,0.313,1.30775,2.2010,2.62500,4.515
Bad Schwartau west,8760.0,10.274179,4.101892,1.566,6.53925,11.0035,13.12600,22.573
St lorenz Nord,8760.0,4.109674,1.640756,0.626,2.61575,4.4015,5.25100,9.029
Strecknitz,8760.0,8.219342,3.281507,1.253,5.23150,8.8030,10.50100,18.058
lubeck Genin,8760.0,8.219342,3.281507,1.253,5.23150,8.8030,10.50100,18.058
Bad Oldesloe,8760.0,3.656803,1.454369,0.559,2.33850,3.9150,4.66400,8.009
Genin sud,8760.0,3.656803,1.454369,0.559,2.33850,3.9150,4.66400,8.009
Marli,8760.0,1.828396,0.727185,0.279,1.16975,1.9570,2.33200,4.004
Einfeld,8760.0,0.494809,0.195981,0.076,0.31800,0.5300,0.63000,1.080
Neumunster nord,8760.0,0.494809,0.195981,0.076,0.31800,0.5300,0.63000,1.080

In [18]:
df_electrodeHeater.describe().T

,count,mean,std,min,25%,50%,75%,max
electrodeHeater,8760.0,4380.500000,2528.938512,1.0,2190.75,4380.5,6570.25,8760.000
Handewitt,8760.0,0.720582,4.124623,0.0,0.00,0.0,0.00,76.786
Schuby west,8760.0,0.720582,4.124623,0.0,0.00,0.0,0.00,76.786
Uw Husum Nord,8760.0,0.496948,2.844540,0.0,0.00,0.0,0.00,52.955
Suderdonn,8760.0,0.496948,2.844540,0.0,0.00,0.0,0.00,52.955
Heide west,8760.0,0.496948,2.844540,0.0,0.00,0.0,0.00,52.955
Brunsbuttel,8760.0,0.248473,1.422270,0.0,0.00,0.0,0.00,26.478
itzehoe West,8760.0,0.248473,1.422270,0.0,0.00,0.0,0.00,26.478
Klixbull Sud,8760.0,0.261997,1.499682,0.0,0.00,0.0,0.00,27.919
Nielbull,8760.0,0.523998,2.999374,0.0,0.00,0.0,0.00,55.838
Lubeck,8760.0,0.523998,2.999374,0.0,0.00,0.0,0.00,55.838
Siems,8760.0,0.158552,0.907551,0.0,0.00,0.0,0.00,16.895
Jardelund,8760.0,0.158552,0.907551,0.0,0.00,0.0,0.00,16.895
Uw Weesby,8760.0,0.634205,3.630197,0.0,0.00,0.0,0.00,67.581
Kiel West,8760.0,0.634205,3.630197,0.0,0.00,0.0,0.00,67.581
Breklum,8760.0,0.199484,1.141851,0.0,0.00,0.0,0.00,21.257
Horstedt,8760.0,0.199484,1.141851,0.0,0.00,0.0,0.00,21.257
Oldersbek,8760.0,0.199484,1.141851,0.0,0.00,0.0,0.00,21.257
Rendsburg Nord,8760.0,0.199484,1.141851,0.0,0.00,0.0,0.00,21.257
Schacht,8760.0,0.199484,1.141851,0.0,0.00,0.0,0.00,21.257
Rendsburg Mitte,8760.0,0.199484,1.141851,0.0,0.00,0.0,0.00,21.257
Uw Nortorf,8760.0,0.199484,1.141851,0.0,0.00,0.0,0.00,21.257
Bornhoved,8760.0,0.199484,1.141851,0.0,0.00,0.0,0.00,21.257
Bad Segeberg,8760.0,0.199484,1.141851,0.0,0.00,0.0,0.00,21.257
Wahlstedt,8760.0,0.199484,1.141851,0.0,0.00,0.0,0.00,21.257
Geschendorf,8760.0,0.196109,1.122532,0.0,0.00,0.0,0.00,20.897
Schlaltanlage Lubeck Sud,8760.0,0.098055,0.561269,0.0,0.00,0.0,0.00,10.449
Lubeck Zentrum,8760.0,0.098055,0.561269,0.0,0.00,0.0,0.00,10.449
St lorenz sud,8760.0,0.098055,0.561269,0.0,0.00,0.0,0.00,10.449
Bad Schwartau west,8760.0,0.245137,1.403164,0.0,0.00,0.0,0.00,26.122
St lorenz Nord,8760.0,0.196109,1.122532,0.0,0.00,0.0,0.00,20.897
Strecknitz,8760.0,0.392219,2.245062,0.0,0.00,0.0,0.00,41.795
lubeck Genin,8760.0,0.392219,2.245062,0.0,0.00,0.0,0.00,41.795
Bad Oldesloe,8760.0,0.245137,1.403164,0.0,0.00,0.0,0.00,26.122
Genin sud,8760.0,0.764316,4.374961,0.0,0.00,0.0,0.00,81.446
Marli,8760.0,0.764316,4.374961,0.0,0.00,0.0,0.00,81.446
Einfeld,8760.0,0.382158,2.187477,0.0,0.00,0.0,0.00,40.723
Neumunster nord,8760.0,0.983396,5.628976,0.0,0.00,0.0,0.00,104.791

In [19]:
df_wind.columns

Index(['onshoreWind', 'Handewitt', 'Schuby west', 'Uw Husum Nord', 'Suderdonn',
       'Heide west', 'Brunsbuttel', 'itzehoe West', 'Klixbull Sud', 'Nielbull',
       'Lubeck', 'Siems', 'Jardelund', 'Uw Weesby', 'Kiel West', 'Breklum',
       'Horstedt', 'Oldersbek', 'Rendsburg Nord'],
      dtype='object')

In [20]:
df_wind= df_wind.rename(columns={"onshoreWind":"onshoreWind_hourly_timestamp"})

In [21]:
#check column names
df_conventionalLoads.columns

Index(['conventionalLoad_households', 'Handewitt', 'Schuby west',
       'Uw Husum Nord', 'Suderdonn', 'Heide west', 'Brunsbuttel',
       'itzehoe West', 'Klixbull Sud', 'Nielbull', 'Lubeck', 'Siems',
       'Jardelund', 'Uw Weesby', 'Kiel West', 'Breklum', 'Horstedt',
       'Oldersbek', 'Rendsburg Nord', 'Schacht', 'Rendsburg Mitte',
       'Uw Nortorf', 'Bornhoved', 'Bad Segeberg', 'Wahlstedt', 'Geschendorf',
       'Schlaltanlage Lubeck Sud', 'Lubeck Zentrum', 'St lorenz sud',
       'Bad Schwartau west', 'St lorenz Nord', 'Strecknitz', 'lubeck Genin',
       'Bad Oldesloe', 'Genin sud', 'Marli', 'Einfeld', 'Neumunster nord '],
      dtype='object')

In [22]:
#change column name
df_conventionalLoads= df_conventionalLoads.rename(columns={"conventionalLoad_households":"conventionalLoad_hourly_timestamp"})

In [23]:
df_electrodeHeater.columns

Index(['electrodeHeater', 'Handewitt', 'Schuby west', 'Uw Husum Nord',
       'Suderdonn', 'Heide west', 'Brunsbuttel', 'itzehoe West',
       'Klixbull Sud', 'Nielbull', 'Lubeck', 'Siems', 'Jardelund', 'Uw Weesby',
       'Kiel West', 'Breklum', 'Horstedt', 'Oldersbek', 'Rendsburg Nord',
       'Schacht', 'Rendsburg Mitte', 'Uw Nortorf', 'Bornhoved', 'Bad Segeberg',
       'Wahlstedt', 'Geschendorf', 'Schlaltanlage Lubeck Sud',
       'Lubeck Zentrum', 'St lorenz sud', 'Bad Schwartau west',
       'St lorenz Nord', 'Strecknitz', 'lubeck Genin', 'Bad Oldesloe',
       'Genin sud', 'Marli', 'Einfeld', 'Neumunster nord '],
      dtype='object')

In [24]:
df_electrodeHeater= df_electrodeHeater.rename(columns={"electrodeHeater":"electrodeHeater_hourly_timestamp"})

In [25]:
df_photovoltaics.columns

Index(['photovoltaics', 'Handewitt', 'Schuby west', 'Uw Husum Nord',
       'Suderdonn', 'Heide west', 'Brunsbuttel', 'itzehoe West',
       'Klixbull Sud', 'Nielbull', 'Lubeck', 'Siems', 'Jardelund', 'Uw Weesby',
       'Kiel West', 'Breklum', 'Horstedt', 'Oldersbek', 'Rendsburg Nord',
       'Schacht', 'Rendsburg Mitte', 'Uw Nortorf', 'Bornhoved', 'Bad Segeberg',
       'Wahlstedt', 'Geschendorf', 'Schlaltanlage Lubeck Sud',
       'Lubeck Zentrum', 'St lorenz sud', 'Bad Schwartau west',
       'St lorenz Nord', 'Strecknitz', 'lubeck Genin', 'Bad Oldesloe',
       'Genin sud', 'Marli', 'Einfeld', 'Neumunster nord '],
      dtype='object')

In [26]:
df_photovoltaics= df_photovoltaics.rename(columns={"photovoltaics":"photovoltaics_hourly_timestamp"})

In [27]:
def clean_numeric_columns(df):
    for col in df.columns:
        # Only try to convert if column looks numeric
        if df[col].dtype == object:
            df[col] = (
                df[col]
                .astype(str)
                .str.strip()        # remove spaces
                .str.replace(",", ".")  # convert comma decimals
            )
        # Try convert to numeric, ignore errors for non-numeric columns
        df[col] = pd.to_numeric(df[col], errors="ignore")
    return df

In [28]:
df_wind = clean_numeric_columns(df_wind)
df_photovoltaics = clean_numeric_columns(df_photovoltaics)
df_conventionalLoads = clean_numeric_columns(df_conventionalLoads)
df_electrodeHeater = clean_numeric_columns(df_electrodeHeater)

C:\Users\user\AppData\Local\Temp\ipykernel_10364\90570616.py:12: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")

In [29]:
filename= "timeseriesdata/wind_data.csv"
df_wind.to_csv(filename, index=False)
filename1= "timeseriesdata/photovoltaic_data.csv"
df_photovoltaics.to_csv(filename1, index=False)
filename2= "timeseriesdata/conventionLoad_data.csv"
df_conventionalLoads.to_csv(filename2, index=False)
filename3= "timeseriesdata/electrodeHeater.csv"
df_electrodeHeater.to_csv(filename3, index=False)